spring:
  datasource:
    url: jdbc:h2:file:./data/evops;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
