server:
  port: 8080

spring:
  application:
    name: evops-base
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:file:./data/evops;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.evops
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.evops: INFO
