-- H2 本地文件数据库初始化脚本。F1 在此基础上补充业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');
