-- H2 本地文件数据库初始化脚本。
-- 地热井回灌试验与井口监测：井组 -> 试验段 -> 监测点 / 回灌班次 -> 监测批次 -> 井口读数（压力/温度/流量/回灌量 + 井口快照）

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('geothermal-1', '地热井回灌试验与井口监测业务表');

-- ============================ 井组 ============================
CREATE TABLE IF NOT EXISTS t_well_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(32) NOT NULL,          -- 业务主键，全局唯一
    group_name VARCHAR(64) NOT NULL,
    location VARCHAR(255),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,           -- 乐观锁版本
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_well_group_code UNIQUE (group_code)
);

-- ============================ 试验段 ============================
CREATE TABLE IF NOT EXISTS t_test_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    well_group_id BIGINT NOT NULL,
    section_code VARCHAR(32) NOT NULL,        -- 关键业务键，全局唯一
    section_name VARCHAR(64) NOT NULL,
    interval_top_m DECIMAL(10,2),             -- 试验段顶界(米)
    interval_bottom_m DECIMAL(10,2),          -- 试验段底界(米)
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_section_code UNIQUE (section_code),
    CONSTRAINT fk_section_group FOREIGN KEY (well_group_id) REFERENCES t_well_group(id)
);

-- ============================ 监测点 ============================
CREATE TABLE IF NOT EXISTS t_monitor_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_section_id BIGINT NOT NULL,
    point_code VARCHAR(32) NOT NULL,          -- 关键业务键，全局唯一
    point_name VARCHAR(64) NOT NULL,
    well_name VARCHAR(64) NOT NULL,           -- 对应的地热井名称
    point_type VARCHAR(16) NOT NULL DEFAULT 'WELLHEAD',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_monitor_point_code UNIQUE (point_code),
    CONSTRAINT fk_point_section FOREIGN KEY (test_section_id) REFERENCES t_test_section(id)
);

-- ============================ 回灌班次 ============================
CREATE TABLE IF NOT EXISTS t_reinjection_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_section_id BIGINT NOT NULL,
    shift_date DATE NOT NULL,                 -- 业务日期
    shift_index INT NOT NULL,                 -- 当日班次序号
    shift_code VARCHAR(128) NOT NULL,         -- 复合业务键（井组-试验段-日期-班次），唯一
    operator_name VARCHAR(64),
    planned_injection_m3h DECIMAL(12,3),
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reinjection_shift_code UNIQUE (shift_code),
    CONSTRAINT uk_reinjection_shift_cbk UNIQUE (test_section_id, shift_date, shift_index),
    CONSTRAINT fk_shift_section FOREIGN KEY (test_section_id) REFERENCES t_test_section(id)
);

-- ============================ 监测批次 ============================
CREATE TABLE IF NOT EXISTS t_monitor_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL,
    monitor_point_id BIGINT NOT NULL,
    batch_no VARCHAR(128) NOT NULL,           -- 关键业务键（含井组/试验段/班次信息的批次号），唯一
    biz_date DATE NOT NULL,                   -- 业务日期
    wellhead_snapshot CLOB,                   -- 建批时的井口快照（JSON）
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    accepted_version INT,                     -- 验收时冻结的版本快照
    accounting_id BIGINT,                     -- 落账后关联账套标识
    accepted_at TIMESTAMP,
    accepted_by BIGINT,
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_monitor_batch_no UNIQUE (batch_no),
    CONSTRAINT uk_monitor_batch_cbk UNIQUE (shift_id, monitor_point_id, biz_date),
    CONSTRAINT fk_batch_shift FOREIGN KEY (shift_id) REFERENCES t_reinjection_shift(id),
    CONSTRAINT fk_batch_point FOREIGN KEY (monitor_point_id) REFERENCES t_monitor_point(id)
);

-- ============================ 井口读数（压力/温度/流量/回灌量） ============================
CREATE TABLE IF NOT EXISTS t_wellhead_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    reading_time_local TIMESTAMP NOT NULL,    -- 业务时区下的本地时刻
    pressure_mpa DECIMAL(10,3) NOT NULL,      -- 井口压力
    temperature_c DECIMAL(10,3) NOT NULL,     -- 井口温度
    flow_m3h DECIMAL(12,3) NOT NULL,          -- 瞬时流量
    injection_volume_m3 DECIMAL(14,3) NOT NULL, -- 回灌量
    wellhead_snapshot CLOB,                   -- 该条读数的井口快照（JSON）
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reading_batch FOREIGN KEY (batch_id) REFERENCES t_monitor_batch(id)
);

-- ============================ 跨表写入审计（请求号/操作者/业务时区/版本快照） ============================
CREATE TABLE IF NOT EXISTS t_biz_write_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,          -- 请求号，唯一（并发去重/幂等）
    operator_id BIGINT,
    operator_name VARCHAR(64),
    biz_timezone VARCHAR(48) NOT NULL,        -- 业务时区
    object_type VARCHAR(32) NOT NULL,
    object_id BIGINT,
    action VARCHAR(32) NOT NULL,
    version_snapshot CLOB,                    -- 版本快照（涉及对象的版本及关键数据）
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_biz_write_audit_req UNIQUE (request_no)
);
