-- H2 本地文件数据库初始化脚本。
-- 地热井回灌试验与井口监测：井组 -> 试验段 -> 监测点 / 回灌班次 -> 监测批次 -> 井口读数（压力/温度/流量/回灌量 + 井口快照）

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('geothermal-1', '地热井回灌试验与井口监测业务表');

-- ============================ 井组 ============================
CREATE TABLE IF NOT EXISTS t_well_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(32) NOT NULL,          -- 业务主键，全局唯一
    group_name VARCHAR(64) NOT NULL,
    location VARCHAR(255),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,           -- 乐观锁版本
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_well_group_code UNIQUE (group_code)
);

-- ============================ 试验段 ============================
CREATE TABLE IF NOT EXISTS t_test_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    well_group_id BIGINT NOT NULL,
    section_code VARCHAR(32) NOT NULL,        -- 关键业务键，全局唯一
    section_name VARCHAR(64) NOT NULL,
    interval_top_m DECIMAL(10,2),             -- 试验段顶界(米)
    interval_bottom_m DECIMAL(10,2),          -- 试验段底界(米)
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_section_code UNIQUE (section_code),
    CONSTRAINT fk_section_group FOREIGN KEY (well_group_id) REFERENCES t_well_group(id)
);

-- ============================ 监测点 ============================
CREATE TABLE IF NOT EXISTS t_monitor_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_section_id BIGINT NOT NULL,
    point_code VARCHAR(32) NOT NULL,          -- 关键业务键，全局唯一
    point_name VARCHAR(64) NOT NULL,
    well_name VARCHAR(64) NOT NULL,           -- 对应的地热井名称
    point_type VARCHAR(16) NOT NULL DEFAULT 'WELLHEAD',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_monitor_point_code UNIQUE (point_code),
    CONSTRAINT fk_point_section FOREIGN KEY (test_section_id) REFERENCES t_test_section(id)
);

-- ============================ 回灌班次 ============================
CREATE TABLE IF NOT EXISTS t_reinjection_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_section_id BIGINT NOT NULL,
    shift_date DATE NOT NULL,                 -- 业务日期
    shift_index INT NOT NULL,                 -- 当日班次序号
    shift_code VARCHAR(128) NOT NULL,         -- 复合业务键（井组-试验段-日期-班次），唯一
    operator_name VARCHAR(64),
    planned_injection_m3h DECIMAL(12,3),
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reinjection_shift_code UNIQUE (shift_code),
    CONSTRAINT uk_reinjection_shift_cbk UNIQUE (test_section_id, shift_date, shift_index),
    CONSTRAINT fk_shift_section FOREIGN KEY (test_section_id) REFERENCES t_test_section(id)
);

-- ============================ 监测批次 ============================
CREATE TABLE IF NOT EXISTS t_monitor_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL,
    monitor_point_id BIGINT NOT NULL,
    batch_no VARCHAR(128) NOT NULL,           -- 关键业务键（含井组/试验段/班次信息的批次号），唯一
    biz_date DATE NOT NULL,                   -- 业务日期
    wellhead_snapshot CLOB,                   -- 建批时的井口快照（JSON）
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    accepted_version INT,                     -- 验收时冻结的版本快照
    accounting_id BIGINT,                     -- 落账后关联账套标识
    accepted_at TIMESTAMP,
    accepted_by BIGINT,
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_monitor_batch_no UNIQUE (batch_no),
    CONSTRAINT uk_monitor_batch_cbk UNIQUE (shift_id, monitor_point_id, biz_date),
    CONSTRAINT fk_batch_shift FOREIGN KEY (shift_id) REFERENCES t_reinjection_shift(id),
    CONSTRAINT fk_batch_point FOREIGN KEY (monitor_point_id) REFERENCES t_monitor_point(id)
);

-- ============================ 井口读数（压力/温度/流量/回灌量） ============================
CREATE TABLE IF NOT EXISTS t_wellhead_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    reading_time_local TIMESTAMP NOT NULL,    -- 业务时区下的本地时刻
    pressure_mpa DECIMAL(10,3) NOT NULL,      -- 井口压力
    temperature_c DECIMAL(10,3) NOT NULL,     -- 井口温度
    flow_m3h DECIMAL(12,3) NOT NULL,          -- 瞬时流量
    injection_volume_m3 DECIMAL(14,3) NOT NULL, -- 回灌量
    wellhead_snapshot CLOB,                   -- 该条读数的井口快照（JSON）
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reading_batch FOREIGN KEY (batch_id) REFERENCES t_monitor_batch(id)
);

-- ============================ 跨表写入审计（请求号/操作者/业务时区/版本快照） ============================
CREATE TABLE IF NOT EXISTS t_biz_write_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,          -- 请求号，唯一（并发去重/幂等）
    operator_id BIGINT,
    operator_name VARCHAR(64),
    biz_timezone VARCHAR(48) NOT NULL,        -- 业务时区
    object_type VARCHAR(32) NOT NULL,
    object_id BIGINT,
    action VARCHAR(32) NOT NULL,
    version_snapshot CLOB,                    -- 版本快照（涉及对象的版本及关键数据）
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_biz_write_audit_req UNIQUE (request_no)
);

-- ============================================================================
-- 运营检索 / 多租户数据权限 / 秒级井口遥测（第二期）
-- 幂等：schema.sql 每次启动执行，H2 2.x 支持 IF NOT EXISTS 的列与索引追加。
-- ============================================================================

-- ============================ 租户 ============================
CREATE TABLE IF NOT EXISTS t_tenant (
    id BIGINT PRIMARY KEY,                    -- 固定 1/2，便于 DEFAULT 1 回填既有数据
    tenant_code VARCHAR(32) NOT NULL,
    tenant_name VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_code UNIQUE (tenant_code)
);

MERGE INTO t_tenant (id, tenant_code, tenant_name, status) KEY (id)
VALUES (1, 'T1', '关中地热运营公司', 'ACTIVE'),
       (2, 'T2', '河西地热运营公司', 'ACTIVE');

-- 既有业务对象追加租户列（存量数据归属默认租户 1）
ALTER TABLE t_well_group ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE t_test_section ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE t_monitor_point ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE t_reinjection_shift ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE t_monitor_batch ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
-- 批次冗余维度（多对一标量列，非集合，天然不会一对多放大），运营检索单表即可裁剪
ALTER TABLE t_monitor_batch ADD COLUMN IF NOT EXISTS well_group_id BIGINT;
ALTER TABLE t_monitor_batch ADD COLUMN IF NOT EXISTS test_section_id BIGINT;

-- ============================ 对象级授权（多租户只读账号的数据权限） ============================
-- 角色为 TENANT_VIEWER 的账号只能看到被显式授权的对象；TENANT_ADMIN 可见本租户全部对象。
-- 授权按业务对象粒度发放（这里以井组 WELL_GROUP 为授权单元，下级试验段/批次随井组收敛）。
CREATE TABLE IF NOT EXISTS t_object_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    grantee_account VARCHAR(64) NOT NULL,     -- 被授权账号
    object_type VARCHAR(32) NOT NULL,         -- 如 WELL_GROUP
    object_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_object_grant UNIQUE (tenant_id, grantee_account, object_type, object_id)
);

-- ============================ 秒级井口遥测（独立于业务读数的高频事件流） ============================
-- 约 150000 条秒级数据。partition_date 为 reading_time 派生的分区裁剪键（生成列），
-- 聚合查询必须带 partition_date 范围谓词，禁止扫描全表。
CREATE TABLE IF NOT EXISTS t_wellhead_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    well_group_id BIGINT NOT NULL,
    test_section_id BIGINT NOT NULL,
    monitor_point_id BIGINT NOT NULL,
    reading_time TIMESTAMP NOT NULL,           -- 秒级采样时刻
    partition_date DATE GENERATED ALWAYS AS (CAST(reading_time AS DATE)),  -- 日期分区裁剪键
    pressure_mpa DECIMAL(10,3) NOT NULL,       -- 井口压力
    temperature_c DECIMAL(10,3),
    flow_m3h DECIMAL(12,3),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------- 索引：运营检索（确定性主键分页 + 组合条件） ----------------
CREATE INDEX IF NOT EXISTS idx_batch_tenant_date ON t_monitor_batch (tenant_id, biz_date, id);
CREATE INDEX IF NOT EXISTS idx_batch_group_date ON t_monitor_batch (tenant_id, well_group_id, biz_date, id);
CREATE INDEX IF NOT EXISTS idx_batch_section_date ON t_monitor_batch (tenant_id, test_section_id, biz_date, id);
CREATE INDEX IF NOT EXISTS idx_batch_status ON t_monitor_batch (tenant_id, status, biz_date);
CREATE INDEX IF NOT EXISTS idx_batch_shift ON t_monitor_batch (shift_id);
-- 一对多读数侧：批内压力半连接，配合 EXISTS 不放大主表
CREATE INDEX IF NOT EXISTS idx_reading_batch_pressure ON t_wellhead_reading (batch_id, pressure_mpa);
CREATE INDEX IF NOT EXISTS idx_shift_section ON t_reinjection_shift (test_section_id);
CREATE INDEX IF NOT EXISTS idx_group_tenant ON t_well_group (tenant_id);
CREATE INDEX IF NOT EXISTS idx_grant_lookup ON t_object_grant (tenant_id, grantee_account, object_type, object_id);

-- ---------------- 索引：秒级遥测分区裁剪 + 40 井组单查询聚合 ----------------
CREATE INDEX IF NOT EXISTS idx_telem_tenant_partition_group ON t_wellhead_telemetry (tenant_id, partition_date, well_group_id, reading_time);
CREATE INDEX IF NOT EXISTS idx_telem_group_partition_time ON t_wellhead_telemetry (well_group_id, partition_date, reading_time);
CREATE INDEX IF NOT EXISTS idx_telem_point_partition ON t_wellhead_telemetry (monitor_point_id, partition_date);

-- ============================================================================
-- 观测数据 CSV 批量导入（第三期）
-- 文件校验和 + 业务键双重幂等；分片事务（单行失败不回滚整批）；
-- 失败分片可重试 / 断点续传；坏传感器隔离；已锁定/已验收数据禁止覆盖。
-- ============================================================================

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('geothermal-3', '观测数据CSV批量导入（分片/幂等/续传/隔离）');

-- ============================ 导入文件（一次上传 = 一个导入任务） ============================
CREATE TABLE IF NOT EXISTS t_import_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    checksum VARCHAR(64) NOT NULL,            -- 文件内容 SHA-256，文件级幂等键
    content BLOB,                             -- 原始文件内容：断点续传/失败分片重试的数据源
    shard_size INT NOT NULL,                  -- 本分片计划的行数粒度
    total_rows INT NOT NULL DEFAULT 0,        -- 数据行总数（不含表头）
    success_rows INT NOT NULL DEFAULT 0,
    updated_rows INT NOT NULL DEFAULT 0,
    failed_rows INT NOT NULL DEFAULT 0,
    total_shards INT NOT NULL DEFAULT 0,
    done_shards INT NOT NULL DEFAULT 0,
    failed_shards INT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'PROCESSING', -- PROCESSING/COMPLETED/COMPLETED_WITH_ERRORS/FAILED
    message VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_import_file_checksum UNIQUE (tenant_id, checksum)
);

-- ============================ 导入分片（断点续传 / 失败重试的最小单元） ============================
CREATE TABLE IF NOT EXISTS t_import_shard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_id BIGINT NOT NULL,
    shard_index INT NOT NULL,                 -- 0 起始的分片序号
    row_start INT NOT NULL,                   -- 覆盖的原始行号区间 [row_start, row_end]（含表头偏移）
    row_end INT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING', -- PENDING/PROCESSING/SUCCESS/FAILED
    attempt_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(512),               -- 分片级失败原因（基础设施异常；行级失败不算分片失败）
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_import_shard_idx UNIQUE (import_file_id, shard_index),
    CONSTRAINT fk_shard_file FOREIGN KEY (import_file_id) REFERENCES t_import_file(id)
);

-- ============================ 逐行明细（成功/更新/失败 + 原始行号/字段/原值/原因） ============================
CREATE TABLE IF NOT EXISTS t_import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_id BIGINT NOT NULL,
    shard_id BIGINT NOT NULL,
    row_no INT NOT NULL,                      -- 原始 CSV 物理行号（表头为第 1 行）
    object_code VARCHAR(64),
    serial_no VARCHAR(64),
    observed_at_raw VARCHAR(64),              -- 观测时间原始文本
    result VARCHAR(16) NOT NULL,              -- SUCCESS/UPDATED/FAILED
    fail_field VARCHAR(32),                   -- 失败字段（校验失败的列名）
    fail_value VARCHAR(255),                  -- 失败字段原始值
    fail_reason VARCHAR(512),                 -- 失败原因
    biz_key VARCHAR(255),                     -- 业务键（objectCode + serialNo）
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_import_row_no UNIQUE (import_file_id, row_no),  -- 行级幂等：分片重试不重复落明细
    CONSTRAINT fk_row_file FOREIGN KEY (import_file_id) REFERENCES t_import_file(id),
    CONSTRAINT fk_row_shard FOREIGN KEY (shard_id) REFERENCES t_import_shard(id)
);

-- ============================ 井口观测数据（CSV 导入落库目标表） ============================
-- 业务键：(tenant_id, monitor_point_id, serial_no) —— 井口网关重发同序列号时幂等更新；
--          (tenant_id, monitor_point_id, observed_at) —— 同监测点同一观测时刻唯一。
CREATE TABLE IF NOT EXISTS t_wellhead_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    monitor_point_id BIGINT NOT NULL,
    object_code VARCHAR(64) NOT NULL,         -- 对象编号（监测点编码快照）
    serial_no VARCHAR(64) NOT NULL,           -- 网关序列号（序列校验/幂等键分量）
    source_device VARCHAR(64) NOT NULL,       -- 来源设备
    observed_at TIMESTAMP NOT NULL,           -- 观测时间（业务时区本地时刻）
    biz_date DATE NOT NULL,                   -- 业务日期（observed_at 派生，跨天补报按观测日落账）
    pressure_mpa DECIMAL(10,3) NOT NULL,      -- 井口压力（MPa）
    temperature_c DECIMAL(10,3) NOT NULL,     -- 温度（℃）
    flow_m3h DECIMAL(12,3) NOT NULL,          -- 流量（m³/h）
    injection_volume_m3 DECIMAL(14,3) NOT NULL, -- 回灌量（m³）
    import_file_id BIGINT NOT NULL,           -- 最近一次写入来源
    row_no INT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_obs_point_serial UNIQUE (tenant_id, monitor_point_id, serial_no),
    CONSTRAINT uk_obs_point_time UNIQUE (tenant_id, monitor_point_id, observed_at),
    CONSTRAINT fk_obs_point FOREIGN KEY (monitor_point_id) REFERENCES t_monitor_point(id),
    CONSTRAINT fk_obs_file FOREIGN KEY (import_file_id) REFERENCES t_import_file(id)
);

-- ============================ 坏传感器隔离（设备级检疫名单） ============================
CREATE TABLE IF NOT EXISTS t_device_quarantine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,         -- 来源设备编码
    reason VARCHAR(255),
    status VARCHAR(16) NOT NULL DEFAULT 'QUARANTINED', -- QUARANTINED/RELEASED
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_device_quarantine UNIQUE (tenant_id, device_code)
);

-- ---------------- 索引：导入域 ----------------
CREATE INDEX IF NOT EXISTS idx_shard_file_status ON t_import_shard (import_file_id, status);
CREATE INDEX IF NOT EXISTS idx_row_file_result ON t_import_row (import_file_id, result, row_no);
CREATE INDEX IF NOT EXISTS idx_row_shard ON t_import_row (shard_id);
CREATE INDEX IF NOT EXISTS idx_obs_point_date ON t_wellhead_observation (tenant_id, monitor_point_id, biz_date);
CREATE INDEX IF NOT EXISTS idx_obs_file ON t_wellhead_observation (import_file_id);
